name: Flatpak Builder

on:
  workflow_dispatch:


jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: raspirus.flatpak
        manifest-path: flatpak/io.github.raspirus.raspirus.yml
        cache-key: flatpak-builder-${{ github.sha }}
